### ISSUE TITLE
How to output throughput? 

### ISSUE THREAD

**Issue by H-L320** [bft-smart/library#103]
How to output throughput? When I start 4 counter demonstration and then start the client, only the delay is output

**Comment by rvassantlal** [comment]
Counter service is a simple demo to show how to use BFT-SMaRt.
To measure throughput, use classes present in the package [src/main/java/bftsmart/demo/microbenchmarks](https://github.com/bft-smart/library/tree/master/src/main/java/bftsmart/demo/microbenchmarks).
You can start servers and clients as follow:
```
./smartrun.sh bftsmart.demo.microbenchmarks.ThroughputLatencyServer <processId> <measurement interval> <reply size> <state size> <context?> <nosig | default | ecdsa> [rwd | rw]
./smartrun.sh bftsmart.demo.microbenchmarks.ThroughputLatencyClient <initial client id> <number of clients> <number of operations> <request size> <interval (ms)> <read only?> <verbose?> <nosig | default | ecdsa>
```
Similar to counter demo, start n servers (ThroughputLatencyServer) and clients (ThroughputLatencyClient ) as needed.

**Comment by H-L320** [comment]
![image](https://github.com/bft-smart/library/assets/72146544/04b6a778-8d74-4602-a5f2-3e559ea62e0f)
![image](https://github.com/bft-smart/library/assets/72146544/44a8cc42-81f7-4fcb-a89e-f38447655e3e)
This is my output, I don't know which one represents the true latency and throughput

**Comment by rvassantlal** [comment]
Throughput is observed in leader server (replica 0 in normal execution). This value is presented in "Throughput" row (18.59 op/s in the screenshot you sent).
Since the throughput is printed every 1000 ms in your case, you need to send more requrest to have a good value. Meaning clients should send more that 1k requests.

Regarding latency, it is measured in client. There are two diferent latencies. The first value is the average computed after removing 10% of lowest and highest latency values (10988.298 us in your screenshot). The third value is average of all latencies (12190.170 us).

**Comment by H-L320** [comment]
ok, thank you
