### ISSUE TITLE
Why is there no throughput output?

### ISSUE THREAD

**Issue by Sloanleee** [bft-smart/library#110]
Why is the server not outputting throughput?
I have started servers and clients as：
```
bash runscripts/smartrun.sh bftsmart.demo.microbenchmarks.ThroughputLatencyServer 0 2000 0 0 false nosig rwd 
bash runscripts/smartrun.sh bftsmart.demo.microbenchmarks.ThroughputLatencyClient 1001 1 100 1024 0 false false nosig
```
But server has no print throughput 
![Snipaste_2024-04-16_21-59-25](https://github.com/bft-smart/library/assets/129843609/ec2ebedd-a08f-45a5-b2fd-5bc817831d33)
Only the client outputs the latency
![Snipaste_2024-04-16_21-59-58](https://github.com/bft-smart/library/assets/129843609/3282867f-f8ef-466a-b2a9-b07486604973)

**Comment by rvassantlal** [comment]
```bash runscripts/smartrun.sh bftsmart.demo.microbenchmarks.ThroughputLatencyServer 0 2000 0 0 false nosig rwd```
This command starts servers by setting them to print throughput measurement every 2000 ms (2 s).

```bash runscripts/smartrun.sh bftsmart.demo.microbenchmarks.ThroughputLatencyClient 1001 1 100 1024 0 false false nosig```
This command starts a client to send 100 request.

The problem is the servers process 100 requests very fast. Takes them less than 2 s to process. That is why the server does not print the throughput.
Increase the number of requests for example to 1000000 or decrease the interval in servers from 2s to less.

**Comment by Sloanleee** [comment]
OK, thank you for your reply.
