### ISSUE TITLE
Malicious Byzantine fault support

### ISSUE THREAD

**Issue by adagys** [bft-smart/library#30]
To what extent are malicious Byztantine faults tolerated in the current version?
I've seen the config options for enabling the bft mode and message signing, but looking at the code, for example, https://github.com/bft-smart/library/blob/master/src/bftsmart/communication/client/netty/NettyClientServerCommunicationSystemServerSide.java#L265,
replies from replicas seem to never get signed.

**Comment by jcs47** [comment]
That is because the signing or MAC creating isn't done there. It is doen at the Netty encoder:

https://github.com/bft-smart/library/blob/master/src/bftsmart/communication/client/netty/NettyTOMMessageEncoder.java

Similarly, verification is done at the decoder:

https://github.com/bft-smart/library/blob/master/src/bftsmart/communication/client/netty/NettyTOMMessageDecoder.java

**Comment by adagys** [comment]
I still don't see signing done at the encoder, but in general only client requests get signed, right? In which case everything's clear.

**Comment by jcs47** [comment]
Exactly. digital signatures are performed only by clients (if the library is configured to do so). The replies sent by replicas are authenticated with MACs.

**Comment by adagys** [comment]
ok, thanks for clarifying!
