### ISSUE TITLE
Bft smart creates ordered message out of unordered response

### ISSUE THREAD

**Issue by Raycoms** [bft-smart/library#34]
In our project we sent a semiEmpty response with only one byte "1" to the server.
This somehow triggered an ordered message.

I believe that shouldn't be this way.

**Comment by jcs47** [comment]
That is not happening in my end. Are you sure that (a) the servers are replying with the same value, or (b) that the value isn't being modified due to concurrent ordered requests? The client may indeed need to re-issue a unordered request, but only if it is unable to receive the same value from n-f replicas (which may happen under the aforementioned scenarios).

**Comment by Raycoms** [comment]
This happens on my end, when a Server replies to an unordered request with
the value "0" or "1".

2017-04-12 15:13 GMT-03:00 jcs47 <notifications@github.com>:

**Comment by jcs47** [comment]
But what about the scenarios that I just asked you about?

**Comment by Raycoms** [comment]
No, the returned values should all be the same. But even if not, should the
client create an ordered request out of an unordered one?

2017-04-12 15:18 GMT-03:00 jcs47 <notifications@github.com>:

**Comment by jcs47** [comment]
If the client doesn't receive n-f replies from the servers with the same value, then yes, the client does need to re-issue the unordered request as an ordered one.

**Comment by Raycoms** [comment]
Okay shouldn't that be configurable in the config?

I feel like there should be a way to a) Resend unordered or b) Resend
ordered.



2017-04-12 15:27 GMT-03:00 jcs47 <notifications@github.com>:

**Comment by jcs47** [comment]
No, it shouldn't, because it is not an utility, it is a matter of protocol correctness.
