### ISSUE TITLE
Byzantine simulation on appExecuteUnordered

### ISSUE THREAD

**Issue by fmmagalhaes** [bft-smart/library#35]
I'm simulating a byzantine behaviour in one of my replicas in a get request in appExecuteUnordered.

It seems that if one replica returns a different value, every replica tries to execute appExecuteBatch with that same get request.

This is my implementation of appExecuteBatch:

@Override
    public byte[][] appExecuteBatch(byte[][] bytes, MessageContext[] messageContexts) {
        byte[][] replies = new byte[bytes.length][];
        for (int i = 0; i < bytes.length; i++)
            replies[i] = executeSingle(bytes[i], messageContexts[i]);
        return replies;
    }

For some reason, if one replica returns a different value, the ServiceProxy object gets a null value. Is that suppose to happen?

**Comment by jcs47** [comment]
The service proxy is indeed supposed to issue an ordered request in case it is unable to obtain a quorum of replies for the same value.

Assuming your setup is N=4 and F=1, if the service proxy gets N-F replies for an unordered request wherein not all of them contain the same value, it will re-issue the request as a ordered request, which will trigger appExecuteBatch at the replicas.

This needs to happen because unordered requests are delivered concurrently with ordered requests, and since ordered requests are supposed to modify the state, the same unordered request might observe different states in different replicas. Hence, it is possible for the client to not be able to receive N-F matching replies. Since in you system you make one of the replicas to exhibit Byzantine behaviour, you end up forcing the scenario I just described.

**Comment by fmmagalhaes** [comment]
In my system, I have N = 6 and F = 1. The ServiceProxy returns null everytime the byzantine replica acts. If it supports 1 faulty replica, as I want to display the right value, should I have the same request both in executeSingle and in appExecuteUnordered?

**Comment by jcs47** [comment]
Yes you should, because there is always a chance that due to the concurrency that I described, that the request requires to pass through the total order protocol. Also, I re-check the code, and the library is even more aggressive under this scenario than I remembered: it doesn't even wait for N-F. It re-issues the requests immediately after receiving a reply that doesn't match the ones that already received. It is still a correct behavior, though.

**Comment by fmmagalhaes** [comment]
I suppose it does wait for N-F replies if it's an ordered request, although this is not the case if we're talking about unordered requests. 

I now deal with my request in both methods and the system behaves as expected, tolerating F faults.

Thank you!

**Comment by jcs47** [comment]
De nada!
