### ISSUE TITLE
Timeout on multithreaded load

### ISSUE THREAD

**Issue by luisfrpereira** [bft-smart/library#47]
I am doing load tests on BFT-SMART and I am having timeouts when I load more than one thread.
1000 // 0 // TIMEOUT // Replies received: 0
1000 // 0 // TIMEOUT // Replies received: 0
1000 // 0 // TIMEOUT // Replies received: 0

[ProcessorClient_NOP_LOAD - Cópia.txt](https://github.com/bft-smart/library/files/1253709/ProcessorClient_NOP_LOAD.-.Copia.txt)

Everyting works fine with one thread, but with more than one thread I get long waits calling appExecuteOrdered method.

**Comment by jcs47** [comment]
It seems you are using the same client ID for all threads. Make sure you supply each client with a different ID.

**Comment by luisfrpereira** [comment]
Thanks

Now I tried with 100 threads and I get dozens of timeouts and no CPU load.

63 // 0 // TIMEOUT // Replies received: 2
17 // 0 // TIMEOUT // Replies received: 2
79 // 0 // TIMEOUT // Replies received: 2
4 // 0 // TIMEOUT // Replies received: 2
35 // 0 // TIMEOUT // Replies received: 2
44 // 0 // TIMEOUT // Replies received: 2
2 // 0 // TIMEOUT // Replies received: 2
43 // 0 // TIMEOUT // Replies received: 2
25 // 0 // TIMEOUT // Replies received: 2
12 // 0 // TIMEOUT // Replies received: 2
59 // 0 // TIMEOUT // Replies received: 2
7 // 0 // TIMEOUT // Replies received: 2
.....
.....
and so on...

**Comment by jcs47** [comment]
This time the timeouts are due to clients not receiving enough replies from the replicas. and that is happening right during the first request they send. Assuming you configured the system with 4 replicas, the clients need to be able to gather at least 3 replies for each request issued.

Are you sure all 4 replicas are ready and executing correctly? Also, if you have been fiddling with the config/hosts.config and config/system.config files to update the IP addresses of the replicas you use, make sure you erase the config/currentView file from both the clients and the replicas before you start the experiments. Clients and replicas always prioritize the content of currentView if such file already exists, and if there is a mismatch between that file and the *.config files. you may run into problems.

**Comment by luisfrpereira** [comment]
I tried what you suggested and I still get timeouts on multi threaded requests. I am using 4 replicas.

**Comment by jcs47** [comment]
What program are you using for your load tests? Are y ou using one of the micro-benchmarks available in the demo package of the library, or did you create your own program? If you are using another program, try using the available demos instead. Here it is an example usage:

./runscripts/smartrun.sh bftsmart.demo.microbenchmarks.ThroughputLatencyServer 0 1000  0 0 false

./runscripts/smartrun.sh bftsmart.demo.microbenchmarks.ThroughputLatencyServer 1 1000 0 0 false 

./runscripts/smartrun.sh bftsmart.demo.microbenchmarks.ThroughputLatencyServer 2 1000 0 0 false

./runscripts/smartrun.sh bftsmart.demo.microbenchmarks.ThroughputLatencyServer 3 1000 0 0 false

./runscripts/smartrun.sh bftsmart.demo.microbenchmarks.ThroughputLatencyClient 100 1001 1000000 0 0 false false false

**Comment by luisfrpereira** [comment]
I created a client which I use for test only
The client class is attached to the first message of this thread


My Idea is to call the method appExecuteOrdered which contains an implementation I developed. The Idea is to get benchmarks of the code I have written.

For now, I am calling appExecuteOrdered with an almost empty payload so I am basically testing the latency of BFT-SMART.
