### ISSUE TITLE
Client side is not reading the hosts.config file

### ISSUE THREAD

**Issue by VhLucena** [bft-smart/library#69]
The client code is not reading the server configurations (ip and port) from hosts.config file. Why it's happening?

**Comment by jcs47** [comment]
Probably because it is fetching the server configuration from the config/currentView file instead. Check the log messages. If you are getting this message during start-up:

```
-- Creating current view from configuration file
```

It is because that file does not exist yet, so it will be created based on the contents of hosts.config and system.config. If instead you get this message:

```
-- Using view stored on disk
```

It is ignoring the \*.config files and reading from config/currentView. From the README file:

>**Important tip 6:** Never forget to delete the config/currentView file after you modify config/hosts.config or config/system.config. If config/currentView exists, BFT-SMaRt always fetches the group configuration from this file first. Otherwise, BFT-SMaRt fetches information from the other files and creates config/currentView from scratch. Note that config/currentView only stores information related to the group of replicas. You do not need to delete this file if, for instance, you want to enable the debugger or change the value of the request timeout.

**Comment by VhLucena** [comment]
Perfect! I forgot to delete the curentView file. Thanks so much
