### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by shaozhuguang** [bft-smart/library#75]
We are developing part of the project on the basis of your project. We hope to exchange some questions with you.

1. At present, there is no principal in the License file on your side. I hope you can modify it on your side, because in terms of legitimacy, we need to copy License on your side.

2. We have made some adjustments to your code, aiming at the BFT-SMaRt v1.1-beta version, mainly including the following:

 +  Converting the project to a maven project;

 +  The security of the system configuration loaded by consensus nodes is judged.

 +  Improving the thread security of consensus nodes (the definition of some attributes is not thread-safe);

 +  Modified the response mechanism to unify the response according to the timing of block chains.

 +  When the consensus node starts, it needs to transfer state first. When the consensus ID number of the request is exactly the multiple of checkpoint_period in the configuration file, the failure of updating state will occur, which has been modified.

 +  Remove unnecessary dependencies.

Looking forward to your reply~

**Comment by jcs47** [comment]
We will update the licence, but first we need to figure out what principal to include (not sure if the faculty or the authors of the project). As for your adjustments, the code already went through a lot of updates since v1.1-beta version, so there is potential for a lot of conflicts in the code if you were to create a pull requests. In the meantime, could you give more insight into the response mechanism modifications?

**Comment by shaozhuguang** [comment]
@jcs47  Thanks for your reply~
You can see https://github.com/blockchain-jd-com/bftsmart for more informations.
We use bftsmart as a consensus algorithm for block chains.
We can use the BFT-SMaRt v1.1-beta , so we don't need to update the version for the time being.

Thanks again~
