### ISSUE TITLE
 Re-transmitting STOP message to install regency 

### ISSUE THREAD

**Issue by johnarakas** [bft-smart/library#92]
I am trying to do an evaluation of the system for a project. I am working on an older version of bft smart (with ant, gradle didn't work) and I keep receiving this message: Re-transmitting STOP message to install regency 1. Can anyone help me (i know this is not the write place but where else to speak for bft smart)

**Comment by rvassantlal** [comment]
Regarding Gradle, what version of JDK are you using to compile the code? I can successfully compile using OpenJDK 11.

Regarding STOP messages, does this happen with few clients or when the system is loaded with many clients/requests? A possible reason is system.totalordermulticast.timeout parameter in config/system.config file is low to handle many requests. Since the leader is overloaded, timeout is triggered at the other replicas for the clients' requests, which triggers the leader chance protocol.

I recommend reading the following explaining: [https://github.com/bft-smart/library/wiki/Deployment-Guidelines#adjust-the-requests-timeout-to-your-own-system](https://github.com/bft-smart/library/wiki/Deployment-Guidelines#adjust-the-requests-timeout-to-your-own-system).

If you still have the problem, please specify your experiment configuration (nº of replicas, faults, and clients).
